### ISSUE TITLE
Project crashes

### ISSUE THREAD

**Issue by ar06x** [SauravDharwadkar/heroku-code-server#2]
```
2020-12-10T17:29:33.859233+00:00 heroku[web.1]: State changed from up to down
2020-12-10T17:29:34.694154+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-12-10T17:29:34.780203+00:00 heroku[web.1]: Process exited with status 143
```
This happens everytime, I do not know the reason, nor do I know how to fix it, once this happens I have no idea how to fix it. Heroku also says that the app is suspended. 

What I was doing:
Had fresh code-server page up, wasnt currently doing anything at all.

**Comment by SauravDharwadkar** [comment]
https://www.heroku.com/policy/aup
Heroku actively suspending apps for abusing policy or something

I haven't encountered that problem with this repo , but it start happening .

Heroku literally sell 5gb s3 bucket for 5$ so that's reason dev/ moderator actively suspending app or uses algorithm to do stuff.

I'll be look for some plugins for other way that heroku won't suspend app

**Comment by ar06x** [comment]
@SauravDharwadkar Is it possible the sftp server is the issue? This is my complete log: 
```
2020-12-10T17:44:45.781566+00:00 app[web.1]: [2020-12-10T17:44:45.781Z] info  HTTP server listening on http://0.0.0.0:52219
2020-12-10T17:44:45.782674+00:00 app[web.1]: [2020-12-10T17:44:45.782Z] info      - Using password from $PASSWORD
2020-12-10T17:44:45.783401+00:00 app[web.1]: [2020-12-10T17:44:45.783Z] info      - To disable use `--auth none`
2020-12-10T17:44:45.784102+00:00 app[web.1]: [2020-12-10T17:44:45.783Z] info    - Not serving HTTPS
2020-12-10T17:44:45.873335+00:00 heroku[web.1]: State changed from starting to up
2020-12-10T17:44:45.976447+00:00 app[web.1]: 2020/12/10 20:44:45 NOTICE: SFTP server listening on 127.0.0.1:2022
2020-12-10T17:46:54.620718+00:00 heroku[web.1]: State changed from up to down
2020-12-10T17:46:56.344731+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-12-10T17:46:56.495625+00:00 heroku[web.1]: Process exited with status 143
```
A few seconds after the sftp server starts, the status changes from up to down. 

I used another code-server repo and I didn't have this issue. The reason I chose this one is because it looks way more updated and the other only saved files to itself, so when the dyno restarted all files would be lost.

**Comment by SauravDharwadkar** [comment]
yes , sftp is the problem actually sftp server created by using rclone serve method so its the same thing heroku suspending apps

**Comment by SauravDharwadkar** [comment]
You can try one thing , re-generat rclone.config file and use that, 
Idk but my app is still running

**Comment by ar06x** [comment]
@SauravDharwadkar I attempted to re-create the config file, I first used dropbox, then I tested with drive. The same thing happened with both of them.

**Comment by SauravDharwadkar** [comment]
I'll try to diploy with other heroku account if it get suspended again I'll use python or other any api to do stuff

**Comment by ar06x** [comment]
@SauravDharwadkar Looking into other apps that got suspended, it seems to only happen around the deploy time, which is probably the reason your app still currently works. 

(heroku.com/policy/aup)
> Use the Service to access a third party web property for the purposes of web scraping, web crawling, web monitoring, or other similar activity through a web client that does not take commercially reasonable efforts to: identify itself via a unique User Agent string describing the purpose of the web client; and obey the robots exclusion standard (also known as the robots.txt standard), including the crawl-delay directive;

This is probably the reason the app gets suspended, rclone attempts to access the site where the files are stored and heroku automatically stops and suspends the app. It would have to:

> identify itself via a unique User Agent string describing the purpose of the web client; and obey the robots exclusion standard (also known as the robots.txt standard), including the crawl-delay directive;

In order to not get suspended by heroku.

**Comment by SauravDharwadkar** [comment]
6253bd4c0fe328646ae50bcd0db16d52072b8cbe

this will now  generate unique keys each time , try after 24h of app suspended and let me know 

after deploying app from other account it suspended , i suspect bcz i'm using same key

**Comment by ar06x** [comment]
Nice! It seems to work, but I would kind of like to have the latest version of NodeJS, but trying to install the latest version from nodesource doesn't work. 

```
  RUN curl -sL https://deb.nodesource.com/setup_15.x | bash - \
      apt-get install -y nodejs
```

**Comment by SauravDharwadkar** [comment]
You can always add this line after initial apt install or add node js in existing one
` RUN   apt-get install -y nodejs  `
If you want specific version i think you can use deb file to install or some node js version control or something that manage version 

Any way in your code you should put && after bash - 
Check Docker RUN  syntax and some linux tip tricks to do stuff in single line
