### ISSUE TITLE
Trouble Getting Started - New to rclone [question,help]

### ISSUE THREAD

**Issue by realafierro** [SauravDharwadkar/heroku-code-server#4]
When configuring rclone, I'm asked to choose between 40 types of storage. Which do I pick?

**Comment by SauravDharwadkar** [comment]
That's totally upto you , you can choose any whichever suits you best . At the end rclone serve storage cloud as ftp and access by sftp vscode extension

**Comment by realafierro** [comment]
> That's totally upto you , you can choose any whichever suits you best . At the end rclone serve storage cloud as ftp and access by sftp vscode extension

will rclone set up a storage cloud for me? do i not need to have a membership with whichever cloud service i choose to use?

**Comment by SauravDharwadkar** [comment]
Most of them are free cloud provider , eg google drive 15GB , mega 50GB* , dropbox 5GB , onedrive 5GB , those are popular and there are more , you use rclone to login / authorise your account and generate creadentials for future login and those credentials transfer from local to heroku using BASE_CONF , also read rclone documentation for further help
