### ISSUE TITLE
Config Saving on Restarts

### ISSUE THREAD

**Issue by capriciousduck** [SauravDharwadkar/heroku-code-server#7]
The dynos are automatically restarted after 24 hours. In that case, how can the config of vscode still persist? Will the config be saved in "/home/coder" directory?

Currently, I am using rclone via google drive. On the next deployment, I don't see already created python ".py" files in the Heroku instance but the files are present on my google drive.

**Comment by SauravDharwadkar** [comment]
Vscode config store in project folder in .vscode file ( api keys path and stuff ) , so config sync with rclone cloud storage.
If you want to specific extension or application pre-installed ( normally extension installed by user after deploy will be reset after 30 min of inactivity ) .
Best solution is to fork repo edit docker file and deploy , use readme for help .

**Comment by capriciousduck** [comment]
What about the files I create? For example, I created hello.py file. Will
this file be synced after redeployment, along with other settings?

**Comment by capriciousduck** [comment]
I created a "hello.py" file in the `/home/coder` directory and restarted the dyno. Now I don't see the hello.py file in the vscode session but the file is present in my google drive. Please help.

**Comment by SauravDharwadkar** [comment]
I'll look into that

**Comment by capriciousduck** [comment]
Ok. Thanks.

**Comment by capriciousduck** [comment]
Is the code updated to fix the issue?

**Comment by SauravDharwadkar** [comment]
> I created a "hello.py" file in the `/home/coder` directory and restarted the dyno. Now I don't see the hello.py file in the vscode session but the file is present in my google drive. Please help.

you have to open file in sftp extension , there are other extention they intigrate with workspace but dont work properly if you find any which work better then let me know .
here more about extension https://marketplace.visualstudio.com/items?itemName=liximomo.sftp
![remote-explorer](https://user-images.githubusercontent.com/45504629/144706751-4f06700c-3d44-40ba-9c3c-ab1ac19e669a.png)
 ,
