### ISSUE TITLE
Speed up build times

### ISSUE THREAD

**Issue by artemiszuk** [SauravDharwadkar/heroku-code-server#8]
I suggest you to use a custom base image, prebuilt with all dependancies to vastly improve build speed

**Comment by SauravDharwadkar** [comment]
it's strickly developed around heroku , also it template where anyone want to host there own instance they should fork repo modify docker like adding removing base apt packages (thats why stick to ubuntu rather than alpine ) and vscode plugins to create there own custom coding env
